### ISSUE TITLE
WMI Provider Host causes high CPU usage (Windows 10)

### ISSUE THREAD

**Issue by maggot9779** [retrospy/RetroSpy#189]
After running the software, WMI Provider Host jumps to around 20-30% CPU usage in the Task Manager. I know it is RetroSpy causing the issue because if I close the software, WMI Provider Host goes back to normal low levels. 

It doesn't matter if the software is displaying the skin or not, the CPU usage is still high.

I've tried version 4.1 and 4.2.3, there's no difference. 

This does not happen with NintendoSpy.

**Comment by zoggins** [comment]
I see it jump to 10% on my box, but I will take a look at what is causing it.  Thanks!

From: maggot9779 ***@***.***>
Sent: Monday, July 19, 2021 11:17
To: retrospy/RetroSpy ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [retrospy/RetroSpy] WMI Provider Host causes high CPU usage (Windows 10) (#189)


After running the software, WMI Provider Host jumps to around 20-30% CPU usage in the Task Manager. I know it is RetroSpy causing the issue because if I close the software, WMI Provider Host goes back to normal low levels.

It doesn't matter if the software is displaying the skin or not, the CPU usage is still high.

I've tried version 4.1 and 4.2.3, there's no difference.

This does not happen with NintendoSpy.

**Comment by zoggins** [comment]
What is interesting is that it happens at the setup window before any spying starts.

From: maggot9779 ***@***.***>
Sent: Monday, July 19, 2021 11:17
To: retrospy/RetroSpy ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [retrospy/RetroSpy] WMI Provider Host causes high CPU usage (Windows 10) (#189)


After running the software, WMI Provider Host jumps to around 20-30% CPU usage in the Task Manager. I know it is RetroSpy causing the issue because if I close the software, WMI Provider Host goes back to normal low levels.

It doesn't matter if the software is displaying the skin or not, the CPU usage is still high.

I've tried version 4.1 and 4.2.3, there's no difference.

This does not happen with NintendoSpy.

**Comment by zoggins** [comment]
I bet I know what is causing it, but I need to verify.  It’s the code that auto detects the Arduino/Teensy in the setup window.  The odd thing is that is seems to continue running once the setup window has closed.

From: maggot9779 ***@***.***>
Sent: Monday, July 19, 2021 11:17
To: retrospy/RetroSpy ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [retrospy/RetroSpy] WMI Provider Host causes high CPU usage (Windows 10) (#189)


After running the software, WMI Provider Host jumps to around 20-30% CPU usage in the Task Manager. I know it is RetroSpy causing the issue because if I close the software, WMI Provider Host goes back to normal low levels.

It doesn't matter if the software is displaying the skin or not, the CPU usage is still high.

I've tried version 4.1 and 4.2.3, there's no difference.

This does not happen with NintendoSpy.

**Comment by zoggins** [comment]
Hmmm its not that either.  I will continue to investigate.

From: maggot9779 ***@***.***>
Sent: Monday, July 19, 2021 11:17
To: retrospy/RetroSpy ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [retrospy/RetroSpy] WMI Provider Host causes high CPU usage (Windows 10) (#189)


After running the software, WMI Provider Host jumps to around 20-30% CPU usage in the Task Manager. I know it is RetroSpy causing the issue because if I close the software, WMI Provider Host goes back to normal low levels.

It doesn't matter if the software is displaying the skin or not, the CPU usage is still high.

I've tried version 4.1 and 4.2.3, there's no difference.

This does not happen with NintendoSpy.

**Comment by zoggins** [comment]
Found it.  The timer that polls the serial ports now stops once the viewer starts.  This will go out in the next release which will be soon.

From: Christopher Mallery
Sent: Monday, July 19, 2021 11:39
To: retrospy/RetroSpy ***@***.***>; retrospy/RetroSpy ***@***.***>
Cc: Subscribed ***@***.***>
Subject: RE: [retrospy/RetroSpy] WMI Provider Host causes high CPU usage (Windows 10) (#189)

Hmmm its not that either.  I will continue to investigate.

From: maggot9779 ***@***.******@***.***>>
Sent: Monday, July 19, 2021 11:17
To: retrospy/RetroSpy ***@***.******@***.***>>
Cc: Subscribed ***@***.******@***.***>>
Subject: [retrospy/RetroSpy] WMI Provider Host causes high CPU usage (Windows 10) (#189)


After running the software, WMI Provider Host jumps to around 20-30% CPU usage in the Task Manager. I know it is RetroSpy causing the issue because if I close the software, WMI Provider Host goes back to normal low levels.

It doesn't matter if the software is displaying the skin or not, the CPU usage is still high.

I've tried version 4.1 and 4.2.3, there's no difference.

This does not happen with NintendoSpy.

**Comment by maggot9779** [comment]
Nice. Thanks for looking into it so quickly.
