### ISSUE TITLE
remove broken skins

### ISSUE THREAD

**Issue by MrGamy** [retrospy/RetroSpy#192]
Some skins seem to have stopped working for a while now and should be repaired or removed since they are causing an error message when starting retrospy:

    generic-hitbox-brookeps3ps4tomdsc-ds4-md6b
    generic-hitbox-brooksc-ds4-md6
    generic-hitbox-ds4
    generic-hitbox-xb360
    generic-pattonboxdigital-brookeps3ps4tomdsc-ds4-md6b
    generic-pattonboxdigital-brooksc-ds4-md6
    generic-pattonboxdigital-ds4
![brokenskins](https://user-images.githubusercontent.com/8639512/127480649-5e3e5053-1807-44b1-a21a-e3f9741baa15.png)

**Comment by zoggins** [comment]
In the Help -> About screen what version does it say.  The precision keyword is only supported from 4.1 and up.  Not sure how you got the new skins, but I am betting your .exe is (for some reason) below 4.1.

From: MrGamy ***@***.***>
Sent: Thursday, July 29, 2021 04:18
To: retrospy/RetroSpy ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [retrospy/RetroSpy] remove broken skins (#192)


Some skins seem to have stopped working for a while now and should be repaired or removed since they are causing an error message when starting retrospy:

generic-hitbox-brookeps3ps4tomdsc-ds4-md6b

generic-hitbox-brooksc-ds4-md6

generic-hitbox-ds4

generic-hitbox-xb360

generic-pattonboxdigital-brookeps3ps4tomdsc-ds4-md6b

generic-pattonboxdigital-brooksc-ds4-md6

generic-pattonboxdigital-ds4

[brokenskins]<https://user-images.githubusercontent.com/8639512/127480649-5e3e5053-1807-44b1-a21a-e3f9741baa15.png>

**Comment by MrGamy** [comment]
I am running Version 4.2.3.0
Build Timestamp is 30/07/2021 00:03:12
![about](https://user-images.githubusercontent.com/8639512/127571809-95f7378d-7c90-4661-812a-6deb3db55fd3.png)

**Comment by zoggins** [comment]
Hmmm, that is unexpected.  I will see what I can find, but I can’t repro the error.

**Comment by zoggins** [comment]
Did you delete the skins?  If you didn’t delete them could I get a copy of one of them?

From: Christopher Mallery
Sent: Thursday, July 29, 2021 15:52
To: retrospy/RetroSpy ***@***.***>; retrospy/RetroSpy ***@***.***>
Cc: Comment ***@***.***>
Subject: RE: [retrospy/RetroSpy] remove broken skins (#192)

Hmmm, that is unexpected.  I will see what I can find, but I can’t repro the error.

**Comment by MrGamy** [comment]
here you go - extracted one of the skins but added my whole retrospy folder for good measure.
https://drive.google.com/file/d/1v7cq3xjwguG0pBGLidSd0M-r4AY1Hcf3/view?usp=sharing

**Comment by MrGamy** [comment]
I included my whole retrospy folder in this archive as well. Hope it helps :-)
https://drive.google.com/file/d/1v7cq3xjwguG0pBGLidSd0M-r4AY1Hcf3/view?usp=sharing

**Comment by MrGamy** [comment]
Quick update - I just downloaded the current retrospy-release.zip and opened that fresh install: same error message.
precision seems not to work

**Comment by zoggins** [comment]
Well to add to the confusion I just downloaded your zipped up RetroSpy directory and it starts up fine with the skin in the skin folder.

**Comment by MrGamy** [comment]
haha, awesome! 
That doesn't really help with finding out whats wrong though. D:

**Comment by zoggins** [comment]
still having the problem?

**Comment by zoggins** [comment]
closing from inactivity.  Feel free to repopen if necessary.

**Comment by MrGamy** [comment]
sorry for not responding earlier - yes, this issue is still persistent, I have not checked the nightly build though.
Might there be any dependency I need to have installed on windows?

**Comment by zoggins** [comment]
Another person is having this issue.

**Comment by zoggins** [comment]
What language is your Windows set to?  Is it English or something else?

**Comment by MrGamy** [comment]
My Windows is set to English currently. Secondary Language would be German

**Comment by zoggins** [comment]
When you get a chance could you try this build: https://github.com/retrospy/RetroSpy/releases/tag/diag1

**Comment by zoggins** [comment]
Finally solved this.  It had to do with locale settings expecting a ',' instead of '.' in float numbers.
