### ISSUE TITLE
Crash when no arduino/teensy is found

### ISSUE THREAD

**Issue by 40wattrange** [retrospy/RetroSpy#203]
If i start retrospy without an arduino plugged in, there is the warning that no arduino/teensy is found, but if I then hit the "Go!" button the app crashes rather than giving a warning that there is no arduino present and staying on the initial window.

Only noticed this because I unplugged mine and forgot, then sat here for 10 minutes wondering why it kept crashing haha.

**Comment by zoggins** [comment]
I will take a look, obviously not desired functionality 😊  Thanks

From: 40wattRange ***@***.***>
Sent: Sunday, November 7, 2021 12:00
To: retrospy/RetroSpy ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [retrospy/RetroSpy] Crash when no arduino/teensy is found (Issue #203)


If i start retrospy without an arduino plugged in, there is the warning that no arduino/teensy is found, but if I then hit the "Go!" button the app crashes rather than giving a warning that there is no arduino present and staying on the initial window.

Only noticed this because I unplugged mine and forgot, then sat here for 10 minutes wondering why it kept crashing haha.
